#!/usr/bin/env bash
# Quick network scan
NET="$(ip route | awk '/default/{print $5; exit}')"
IP="$(ip -4 addr show "$NET" 2>/dev/null | awk '/inet /{print $2}')"
SUBNET="${IP%.*}.0/24"
nmap -sn -n "$SUBNET" 2>/dev/null | grep "report for" | awk '{print $5}'
